// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfXwxC5DxzmG1TofTpY7JnL_9tJRnrGHI',
    appId: '1:108977191583:web:031c7133f7a6c6018880aa',
    messagingSenderId: '108977191583',
    projectId: 'tapon-vending',
    authDomain: 'tapon-vending.firebaseapp.com',
    storageBucket: 'tapon-vending.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP0s2ix_8fcELaCvpt5GuXuw1539sksnE',
    appId: '1:108977191583:android:da7385e2833bc1488880aa',
    messagingSenderId: '108977191583',
    projectId: 'tapon-vending',
    storageBucket: 'tapon-vending.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBydKNxSUq9ICK2RfspeY-QL99gvvl15v0',
    appId: '1:108977191583:ios:ffa0b3a15c577bf48880aa',
    messagingSenderId: '108977191583',
    projectId: 'tapon-vending',
    storageBucket: 'tapon-vending.firebasestorage.app',
    androidClientId: '108977191583-p8ja4kf4djgl4t0i7m6bh330qg4v8cq1.apps.googleusercontent.com',
    iosClientId: '108977191583-2rgia4niejr6g0g79njhgvuemnbebv7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.taponVending',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBydKNxSUq9ICK2RfspeY-QL99gvvl15v0',
    appId: '1:108977191583:ios:ffa0b3a15c577bf48880aa',
    messagingSenderId: '108977191583',
    projectId: 'tapon-vending',
    storageBucket: 'tapon-vending.firebasestorage.app',
    androidClientId: '108977191583-p8ja4kf4djgl4t0i7m6bh330qg4v8cq1.apps.googleusercontent.com',
    iosClientId: '108977191583-2rgia4niejr6g0g79njhgvuemnbebv7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.taponVending',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfXwxC5DxzmG1TofTpY7JnL_9tJRnrGHI',
    appId: '1:108977191583:web:88d730323b25b55c8880aa',
    messagingSenderId: '108977191583',
    projectId: 'tapon-vending',
    authDomain: 'tapon-vending.firebaseapp.com',
    storageBucket: 'tapon-vending.firebasestorage.app',
  );

}